### ISSUE TITLE
NoteMarshallerFactory.initFactory() does not find notes.propterties

### ISSUE THREAD

**Issue by cheminux** [fracpete/jcamp-dx#1]
In the classfunction NoteMarshallerFactory.initFactory() the DEFAULT_MARSHALLER is not set since the notes.properties load by:
...
 is = this.getClass().getClassLoader().getResourceAsStream("notes.properties");
     if (is == null)
               return;
....

is alway null. This leads to a nullpointer in the NoteMarshallerFactory.findByDescriptor().

Regards Sven

**Comment by fracpete** [comment]
`NoteMarshallerFactory.DEFAULT_MARSHALLER` now gets initialized with `DefaultNoteMarshaller` class by default. Can you please confirm that this fixes your problem?

**Comment by cheminux** [comment]
Yes I can confirm that the problem is fixed.

Thanks for the fast response!
