### ISSUE TITLE
Remove vecmath dependency

### ISSUE THREAD

**Issue by laeubi** [fracpete/jcamp-dx#8]
Currently the code has a dependency to vecmath. in fact it does only need a class that defines a Point2D and adds some convenience methods to use vecmath classes instead of plain doubles.
To lower the dependecy count and make it mor felxible I would suggest the following changes:
- replace Point2d of vemath by a custom implementation of Point2d
- remove all convenience methods (if one really needs them the can easily created inside some project specific Util class)
- remove vecmath from lib and maven

**Comment by laeubi** [comment]
I'' provide a PR for this.

**Comment by fracpete** [comment]
Release 0.9.6 is out.

**Comment by laeubi** [comment]
Great, thanks :+1:
